package mukhammed;

public class Hibernate {
    public static void main(String[] args) {
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Java 15 is the best");
        System.out.println("Babakhan bayke");
        System.out.println("Baisalbek");
    }
}
